### PR TITLE
Async

### PR DESCRIPTION
**Pull request by mamsdeveloper**
1. Replace aiodeta with deta[async], cause it is official package
2. Fix few bags at AsyncModel
3. Change handle_db_property
4. Rename "PROJECT_KEY" to "DETA_PROJECT_KEY", cause that env variable automatically sets by Deta

### CODE REVIEW

**Comment by rickh94** [comment]
I'm working on merging your commits here. It mostly looks good, however I had to do some work to make my automated tests pass because of the API differences between the old aiodeta and the official deta[async] implementation. 

I am curious why you added constructors for the base model classes. I can't tell how your implementation of the constructor is different from the default constructor provided by pydantic. If something wasn't working without the `__init__` constructor that you added, I would like to know so I can test for it. If not, then I will probably remove the redundant constructors.

**Comment by mamsdeveloper** [comment]
If you about constructor in AsyncDetaModel, I just copied it from DataModel for sameness

**Comment by rickh94** [comment]
I see, that was an inconsistency in my original code. I'm going to merge the changes and push a new version of the library to pypi.

**Comment by rickh94** [comment]
Your changes have been merged and release on pypi as version 1.3.0!

**Pull request merged**
